project_id = "yeomhnubmghjvdjpbiym"

[functions.samco-login]
verify_jwt = false

[functions.angelone-login]
verify_jwt = false

[functions.samco-check-session]
verify_jwt = false

[functions.angelone-check-session]
verify_jwt = false

[functions.shoonya-login]
verify_jwt = false

[functions.shoonya-check-session]
verify_jwt = false

[functions.upstox-auth]
verify_jwt = false

[functions.upstox-check-session]
verify_jwt = false

[functions.get-sessions]
verify_jwt = false

[functions.shoonya-logout]
verify_jwt = false

[functions.samco-logout]
verify_jwt = false

[functions.angelone-logout]
verify_jwt = false

[functions.upstox-logout]
verify_jwt = false

[functions.scheduled-logout]
verify_jwt = false

[functions.scheduled-login]
verify_jwt = false
